# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sukbin Lim
title: Hardware Engineer for AI Accelerators
email: sukbin.lim.4502@gmail.com
# website: sukbin-lim.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username: sukbin-lim
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sukbin-lim
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: google-scholar
  icon: fas fa-graduation-cap
  url: https://scholar.google.com/citations?user=S1YP0lwAAAAJ&hl=ko&oi=ao
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
# about_profile_image: images/profile.jpg
# about_content: | # this will include new lines to allow paragraphs
#   Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

#   I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>
about_content: | # this will include new lines to allow paragraphs
  TODO: Add description about me


content:

  # Title for the section
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: HyperAccel
        sub_title: Hardware Engineer
        caption: 2023 - Present
        description: | # this will include new lines to allow paragraphs
          Adelia
          Bertha-DC
          Bertha-Edge

  # Title for the section
  - title: Education 
    # Type of content section (list/text)
    layout: list
    content:
      - layout: left
        title: KAIST
        sub_title: Ph.D. Electrical Engineering
        caption: Sep.2023 - Sep.2027 (Expected)
        description: | # this will include new lines to allow paragraphs
          Currently researching AI accelerators for efficient LLM serving

          Research Group: CAST Hardware Acceleration Laboratory, KAIST

          Advisor: Prof. Joo-Young Kim

      - layout: left
        title: KAIST
        sub_title: M.S. Electrical Engineering
        caption: Sep.2021 - Aug.2023
        description: | # this will include new lines to allow paragraphs
          Thesis title: Large-scale point cloud deep neural network accelerator with virtual pillar and ROI-based skipping

          Research Group: CAST Hardware Acceleration Laboratory, KAIST

          Advisor: Prof. Joo-Young Kim

      - layout: left
        title: KAIST
        sub_title: B.S. Electrical Engineering
        caption: Mar.2017 - Aug.2021
        description: | # this will include new lines to allow paragraphs
          Key Courses: Computer Architecture, Operating Systems and System Programming, Digital Logic Design

      # - layout: left
      #   title: Jeju Science High School
      #   caption: Mar.2015 - Feb.2017
      #   description: | # this will include new lines to allow paragraphs
      #     Early graduation (completed in 2 years)

  # Title for the section
  - title: Project
    # Type of content section (list/text)
    layout: list
    content:
      - layout: top-middle
        title: Bertha-Edge
        quote: >
          Todo
        description: | # this will include new lines to allow paragraphs
          Todo.

      - layout: top-middle
        title: Bertha-DC
        quote: >
          Todo
        description: | # this will include new lines to allow paragraphs
          Todo.
          
      - layout: top-middle
        title: Adelia
        quote: >
          Todo
        description: | # this will include new lines to allow paragraphs
          Todo.

  # Title for the section
  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      ## **Conference**
      1. Jung-Hoon Kim, **Sukbin Lim**, Junseo Cha, Seungjae Moon, Dongjin Seo, Hunjong Lee, Jongho Kim, Jinwon Lee, Joo-Young Kim, "Adelia: A 4nm LLM Accelerator with Streamlined Dataflow and Dual-Mode Parallelization for Efficient Generative AI Inference", Symposium on VLSI Technology and Circuits (VLSI), 2025, [Link](https://ieeexplore.ieee.org/abstract/document/11075108)
      1. **Sukbin Lim**, Jaehoon Heo, Jinho Yang, Joo-Young Kim, "A 38.5 TOPS/W point cloud neural network processor with virtual pillar and quadtree-based workload management for real-time outdoor BEV detection", IEEE Custom Integrated Circuits Conference (CICC), 2024, [Link](https://ieeexplore.ieee.org/abstract/document/10529067)
      1. Jinho Yang, Sungwoong Yune, **Sukbin Lim**, Donghyuk Kim, Joo-Young Kim, "Acane: An efficient fpga-based embedded vision platform with accumulation-as-convolution packing for autonomous mobile robots", Asia and South Pacific Design Automation Conference (ASP-DAC), 2024, [Link](https://ieeexplore.ieee.org/abstract/document/10473872)
      1. Je Yang, **Sukbin Lim**, Sukjin Lee, Jae-Young Kim, Joo-Young Kim, "JNPU: A 1.04 TFLOPS Joint-DNN Training Processor with Speculative Cyclic Quantization and Triple Heterogeneity on Microarchitecture/Precision/Dataflow", IEEE European Solid State Circuits Conference (ESSCIRC), 2023, [Link](https://ieeexplore.ieee.org/abstract/document/10268810)
      1. Jaehoon Heo, Junsoo Kim, Wontak Han, **Sukbin Lim**, Joo-Young Kim, "T-PIM: A 2.21-to-161.08 TOPS/W processing-in-memory accelerator for end-to-end on-device training", IEEE Custom Integrated Circuits Conference (CICC), 2022, [Link](https://ieeexplore.ieee.org/abstract/document/9772808)
    
      ## **Journal**
      1. Adelia, (Under Review)
      1. **Sukbin Lim**, Jaehoon Heo, Jinho Yang, Joo-Young Kim, "Hawkeye: a point cloud neural network processor with virtual pillar and quadtree-based workload management for real-time outdoor bev detection", IEEE Journal of Solid-State Circuits (JSSC), 2024, [Link](https://ieeexplore.ieee.org/abstract/document/10807164)
      1. Seungjae Moon, Jung-Hoon Kim, Junsoo Kim, Seongmin Hong, Junseo Cha, Minsu Kim, **Sukbin Lim**, Gyubin Choi, Dongjin Seo, Jongho Kim, Hunjong Lee, Hyunjun Park, Ryeowook Ko, Soongyu Choi, Jongse Park, Jinwon Lee, Joo-Young Kim, "Lpu: A latency-optimized and highly scalable processor for large language model inference", IEEE Micro, 2024, [Link](https://ieeexplore.ieee.org/abstract/document/10591630)
      1. Jaehoon Heo, Junsoo Kim, **Sukbin Lim**, Wontak Han, Joo-Young Kim, "T-PIM: An energy-efficient processing-in-memory accelerator for end-to-end on-device training", IEEE Journal of Solid-State Circuits (JSSC), 2022, [Link](https://ieeexplore.ieee.org/abstract/document/9954125)
      1. Wontak Han, Jaehoon Heo, Junsoo Kim, **Sukbin Lim**, Joo-Young Kim, "Design of processing-in-memory with triple computational path and sparsity handling for energy-efficient DNN training", IEEE Journal on Emerging and Selected Topics in Circuits and Systems (JETCAS), 2022, [Link](https://ieeexplore.ieee.org/abstract/document/9760420)

      ## **Patents**
      1. Joint-dnn training processor with speculative quantization and triple heterogeneity, KR102710971B1
      1. Large-scale sparse point cloud neural network accelerator with virtual voxel and roi-based skipping, KR102689248B1
      1. Hardware architecture for accelerating torus fully homomorphic encryption(tfhe) with streaming core and folded fully pipelined fft, KR102616119B9
      1. A Processing-In-Memory Accelerator for End-to-End On-Device Training, KR102576762B1


  # Title for the section
  - title: Awards
    layout: text
    content: | # this will include new lines to allow paragraphs
       1. 2024 Best Paper Award at IEEE Micro
       1. 29th Samsung Human Tech Paper Award Gold Prize in Circuit Design


  # Title for the section
  - title: Others
    layout: text
    content: | # this will include new lines to allow paragraphs
       1. Poster, IDEC Congress CDC, 2024
       1. Journal Reviewer, IEEE Transactions on Circuits and Systems I (TCAS-I), 2023
  

  ## Example
  ## >>>
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Harvard University
  #       caption: 2010 - 2013
  #       sub_title: BSc Computer Science
  #       quote: >
  #         Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  #       description: | # this will include new lines to allow paragraphs
  #         During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  #         I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](images/landscape-trees.jpg "Trees")
  ## <<<
  ## Example

# Footer
footer_show_references: true
references_title: Last Updated @2025-08-16

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
